//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public double Shell_Left {
            get {
                return ((double)(this["Shell_Left"]));
            }
            set {
                this["Shell_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public double Shell_Top {
            get {
                return ((double)(this["Shell_Top"]));
            }
            set {
                this["Shell_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double Shell_Width {
            get {
                return ((double)(this["Shell_Width"]));
            }
            set {
                this["Shell_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double Shell_Height {
            get {
                return ((double)(this["Shell_Height"]));
            }
            set {
                this["Shell_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string Shell_State {
            get {
                return ((string)(this["Shell_State"]));
            }
            set {
                this["Shell_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Shell_StartView {
            get {
                return ((string)(this["Shell_StartView"]));
            }
            set {
                this["Shell_StartView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmpresaID {
            get {
                return ((string)(this["EmpresaID"]));
            }
            set {
                this["EmpresaID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Exp_EstResultados {
            get {
                return ((bool)(this["Exp_EstResultados"]));
            }
            set {
                this["Exp_EstResultados"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Exp_Fibras {
            get {
                return ((bool)(this["Exp_Fibras"]));
            }
            set {
                this["Exp_Fibras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Exp_SitFinanciera {
            get {
                return ((bool)(this["Exp_SitFinanciera"]));
            }
            set {
                this["Exp_SitFinanciera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Exp_FEfec {
            get {
                return ((bool)(this["Exp_FEfec"]));
            }
            set {
                this["Exp_FEfec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Exp_Acciones {
            get {
                return ((bool)(this["Exp_Acciones"]));
            }
            set {
                this["Exp_Acciones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Multiplo {
            get {
                return ((int)(this["Multiplo"]));
            }
            set {
                this["Multiplo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableColAno9 {
            get {
                return ((bool)(this["EnableColAno9"]));
            }
            set {
                this["EnableColAno9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableColAno8 {
            get {
                return ((bool)(this["EnableColAno8"]));
            }
            set {
                this["EnableColAno8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableColAno7 {
            get {
                return ((bool)(this["EnableColAno7"]));
            }
            set {
                this["EnableColAno7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableColAno6 {
            get {
                return ((bool)(this["EnableColAno6"]));
            }
            set {
                this["EnableColAno6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableColAno5 {
            get {
                return ((bool)(this["EnableColAno5"]));
            }
            set {
                this["EnableColAno5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableColAno4 {
            get {
                return ((bool)(this["EnableColAno4"]));
            }
            set {
                this["EnableColAno4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableColAno3 {
            get {
                return ((bool)(this["EnableColAno3"]));
            }
            set {
                this["EnableColAno3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableColAno2 {
            get {
                return ((bool)(this["EnableColAno2"]));
            }
            set {
                this["EnableColAno2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableColAno1 {
            get {
                return ((bool)(this["EnableColAno1"]));
            }
            set {
                this["EnableColAno1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowNumUnidades {
            get {
                return ((bool)(this["EnableRowNumUnidades"]));
            }
            set {
                this["EnableRowNumUnidades"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowCrecimientoUnidades {
            get {
                return ((bool)(this["EnableRowCrecimientoUnidades"]));
            }
            set {
                this["EnableRowCrecimientoUnidades"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowCrecimientoUnidadesP {
            get {
                return ((bool)(this["EnableRowCrecimientoUnidadesP"]));
            }
            set {
                this["EnableRowCrecimientoUnidadesP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowIngresos {
            get {
                return ((bool)(this["EnableRowIngresos"]));
            }
            set {
                this["EnableRowIngresos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowIngUnidad {
            get {
                return ((bool)(this["EnableRowIngUnidad"]));
            }
            set {
                this["EnableRowIngUnidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowCrecIngP {
            get {
                return ((bool)(this["EnableRowCrecIngP"]));
            }
            set {
                this["EnableRowCrecIngP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowCostoVentas {
            get {
                return ((bool)(this["EnableRowCostoVentas"]));
            }
            set {
                this["EnableRowCostoVentas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowUBruta {
            get {
                return ((bool)(this["EnableRowUBruta"]));
            }
            set {
                this["EnableRowUBruta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowMargenBruto {
            get {
                return ((bool)(this["EnableRowMargenBruto"]));
            }
            set {
                this["EnableRowMargenBruto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowGastosOp {
            get {
                return ((bool)(this["EnableRowGastosOp"]));
            }
            set {
                this["EnableRowGastosOp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowUOperativa {
            get {
                return ((bool)(this["EnableRowUOperativa"]));
            }
            set {
                this["EnableRowUOperativa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowMargenOp {
            get {
                return ((bool)(this["EnableRowMargenOp"]));
            }
            set {
                this["EnableRowMargenOp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowGastosFin {
            get {
                return ((bool)(this["EnableRowGastosFin"]));
            }
            set {
                this["EnableRowGastosFin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowUAImpuestos {
            get {
                return ((bool)(this["EnableRowUAImpuestos"]));
            }
            set {
                this["EnableRowUAImpuestos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowImpuestos {
            get {
                return ((bool)(this["EnableRowImpuestos"]));
            }
            set {
                this["EnableRowImpuestos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowUNeta {
            get {
                return ((bool)(this["EnableRowUNeta"]));
            }
            set {
                this["EnableRowUNeta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowUAccionistas {
            get {
                return ((bool)(this["EnableRowUAccionistas"]));
            }
            set {
                this["EnableRowUAccionistas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowCrecUtP {
            get {
                return ((bool)(this["EnableRowCrecUtP"]));
            }
            set {
                this["EnableRowCrecUtP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowMargenNeto {
            get {
                return ((bool)(this["EnableRowMargenNeto"]));
            }
            set {
                this["EnableRowMargenNeto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowIngresosProp {
            get {
                return ((bool)(this["EnableRowIngresosProp"]));
            }
            set {
                this["EnableRowIngresosProp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowNOI {
            get {
                return ((bool)(this["EnableRowNOI"]));
            }
            set {
                this["EnableRowNOI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowFFO {
            get {
                return ((bool)(this["EnableRowFFO"]));
            }
            set {
                this["EnableRowFFO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowAFFO {
            get {
                return ((bool)(this["EnableRowAFFO"]));
            }
            set {
                this["EnableRowAFFO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowMargenNOI {
            get {
                return ((bool)(this["EnableRowMargenNOI"]));
            }
            set {
                this["EnableRowMargenNOI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowMargenFFO {
            get {
                return ((bool)(this["EnableRowMargenFFO"]));
            }
            set {
                this["EnableRowMargenFFO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowMargenAFFO {
            get {
                return ((bool)(this["EnableRowMargenAFFO"]));
            }
            set {
                this["EnableRowMargenAFFO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowNOIAccion {
            get {
                return ((bool)(this["EnableRowNOIAccion"]));
            }
            set {
                this["EnableRowNOIAccion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowFFOAccion {
            get {
                return ((bool)(this["EnableRowFFOAccion"]));
            }
            set {
                this["EnableRowFFOAccion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowAFFOAccion {
            get {
                return ((bool)(this["EnableRowAFFOAccion"]));
            }
            set {
                this["EnableRowAFFOAccion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowEfectivo {
            get {
                return ((bool)(this["EnableRowEfectivo"]));
            }
            set {
                this["EnableRowEfectivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowDeuda {
            get {
                return ((bool)(this["EnableRowDeuda"]));
            }
            set {
                this["EnableRowDeuda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowActivosC {
            get {
                return ((bool)(this["EnableRowActivosC"]));
            }
            set {
                this["EnableRowActivosC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowPasivosC {
            get {
                return ((bool)(this["EnableRowPasivosC"]));
            }
            set {
                this["EnableRowPasivosC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowActivosT {
            get {
                return ((bool)(this["EnableRowActivosT"]));
            }
            set {
                this["EnableRowActivosT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowPasivosT {
            get {
                return ((bool)(this["EnableRowPasivosT"]));
            }
            set {
                this["EnableRowPasivosT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowCapital {
            get {
                return ((bool)(this["EnableRowCapital"]));
            }
            set {
                this["EnableRowCapital"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowCrecCapP {
            get {
                return ((bool)(this["EnableRowCrecCapP"]));
            }
            set {
                this["EnableRowCrecCapP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowACPC {
            get {
                return ((bool)(this["EnableRowACPC"]));
            }
            set {
                this["EnableRowACPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowATPT {
            get {
                return ((bool)(this["EnableRowATPT"]));
            }
            set {
                this["EnableRowATPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PAcidoEnableRow {
            get {
                return ((bool)(this["PAcidoEnableRow"]));
            }
            set {
                this["PAcidoEnableRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowEfDeuda {
            get {
                return ((bool)(this["EnableRowEfDeuda"]));
            }
            set {
                this["EnableRowEfDeuda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowEfCapital {
            get {
                return ((bool)(this["EnableRowEfCapital"]));
            }
            set {
                this["EnableRowEfCapital"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowDeudaAT {
            get {
                return ((bool)(this["EnableRowDeudaAT"]));
            }
            set {
                this["EnableRowDeudaAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowDeudaCapital {
            get {
                return ((bool)(this["EnableRowDeudaCapital"]));
            }
            set {
                this["EnableRowDeudaCapital"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowEfInicio {
            get {
                return ((bool)(this["EnableRowEfInicio"]));
            }
            set {
                this["EnableRowEfInicio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowFOperaciones {
            get {
                return ((bool)(this["EnableRowFOperaciones"]));
            }
            set {
                this["EnableRowFOperaciones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowFInversiones {
            get {
                return ((bool)(this["EnableRowFInversiones"]));
            }
            set {
                this["EnableRowFInversiones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowFFinanciamiento {
            get {
                return ((bool)(this["EnableRowFFinanciamiento"]));
            }
            set {
                this["EnableRowFFinanciamiento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowEfFinal {
            get {
                return ((bool)(this["EnableRowEfFinal"]));
            }
            set {
                this["EnableRowEfFinal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowAccCirc {
            get {
                return ((bool)(this["EnableRowAccCirc"]));
            }
            set {
                this["EnableRowAccCirc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowPrecio {
            get {
                return ((bool)(this["EnableRowPrecio"]));
            }
            set {
                this["EnableRowPrecio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowCapMerc {
            get {
                return ((bool)(this["EnableRowCapMerc"]));
            }
            set {
                this["EnableRowCapMerc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowUPA {
            get {
                return ((bool)(this["EnableRowUPA"]));
            }
            set {
                this["EnableRowUPA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowPU {
            get {
                return ((bool)(this["EnableRowPU"]));
            }
            set {
                this["EnableRowPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowValLibro {
            get {
                return ((bool)(this["EnableRowValLibro"]));
            }
            set {
                this["EnableRowValLibro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowPVL {
            get {
                return ((bool)(this["EnableRowPVL"]));
            }
            set {
                this["EnableRowPVL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowDividendos {
            get {
                return ((bool)(this["EnableRowDividendos"]));
            }
            set {
                this["EnableRowDividendos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowRendDividendos {
            get {
                return ((bool)(this["EnableRowRendDividendos"]));
            }
            set {
                this["EnableRowRendDividendos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRowPTAT {
            get {
                return ((bool)(this["EnableRowPTAT"]));
            }
            set {
                this["EnableRowPTAT"] = value;
            }
        }
    }
}
